// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
<<<<<<< Updated upstream
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
=======
    // @ts-expect-error - getSession exists at runtime but is missing from SupabaseAuthClient type
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
>>>>>>> Stashed changes
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
