// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export function isJwtToken(token: unknown): token is string {
  if (typeof token !== "string") return false;
  const trimmed = token.trim();
  if (!trimmed) return false;
  const parts = trimmed.split(".");
  return parts.length === 3 && parts[0].length > 0 && parts[1].length > 0 && parts[2].length > 0;
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    const authHeader = headers.get("Authorization");
    if (authHeader) {
      const match = authHeader.match(/^Bearer\s+(.+)$/i);
      if (match) {
        const token = match[1].trim();
        // If the bearer token is the opaque publishable key or any non-JWT token, strip it
        if (!isJwtToken(token) || isNewSupabaseApiKey(token) || token === supabaseKey) {
          headers.delete("Authorization");
        }
      } else if (isNewSupabaseApiKey(supabaseKey)) {
        headers.delete("Authorization");
      }
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const metaEnv =
    typeof import.meta !== "undefined" && (import.meta as any).env
      ? (import.meta as any).env
      : ({} as Record<string, string | undefined>);
  const procEnv =
    typeof process !== "undefined" && process.env
      ? process.env
      : ({} as Record<string, string | undefined>);

  const rawUrl =
    metaEnv["VITE_SUPABASE_URL"] || procEnv["SUPABASE_URL"] || procEnv["VITE_SUPABASE_URL"];
  const SUPABASE_URL =
    rawUrl && rawUrl !== "undefined" ? rawUrl : "https://wbbatgbvizhghtkvuguf.supabase.co";

  const rawKey =
    metaEnv["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    metaEnv["VITE_SUPABASE_ANON_KEY"] ||
    procEnv["SUPABASE_PUBLISHABLE_KEY"] ||
    procEnv["VITE_SUPABASE_PUBLISHABLE_KEY"];
  const SUPABASE_PUBLISHABLE_KEY =
    rawKey && rawKey !== "undefined" ? rawKey : "sb_publishable_WiczJQTx4afGJ02WAiUIUw_8YlWjkSP";

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
      accessToken: async () => {
        if (typeof window === "undefined") return null;
        try {
          // 1. Direct check in localStorage for active session token
          const projectRef = new URL(SUPABASE_URL).hostname.split(".")[0];
          const storageKey = `sb-${projectRef}-auth-token`;
          const raw = localStorage.getItem(storageKey);
          if (raw) {
            const parsed = JSON.parse(raw);
            const token = parsed?.access_token || parsed?.currentSession?.access_token;
            if (isJwtToken(token)) return token;
          }

          // 2. Fallback to active in-memory auth session if client is instantiated
          if (_supabase?.auth) {
            const { data } = await _supabase.auth.getSession();
            const token = data?.session?.access_token;
            if (isJwtToken(token)) return token;
          }
        } catch {
          // Never throw, return null to prevent malformed JWT errors
        }
        return null;
      },
    },
  });
}

import type { SupabaseClient } from "@supabase/supabase-js";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ClientWithAuth = Omit<SupabaseClient<Database>, "auth"> & { auth: any };

let _supabase: ClientWithAuth | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ClientWithAuth, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient() as unknown as ClientWithAuth;
    return Reflect.get(_supabase, prop, receiver);
  },
}) as ClientWithAuth;
