// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const metaEnv =
    typeof import.meta !== "undefined" && (import.meta as any).env
      ? (import.meta as any).env
      : ({} as Record<string, string | undefined>);
  const procEnv =
    typeof process !== "undefined" && process.env
      ? process.env
      : ({} as Record<string, string | undefined>);

  const rawUrl =
    metaEnv["VITE_SUPABASE_URL"] ||
    procEnv["SUPABASE_URL"] ||
    procEnv["VITE_SUPABASE_URL"];
  const SUPABASE_URL =
    rawUrl && rawUrl !== "undefined" ? rawUrl : "https://wbbatgbvizhghtkvuguf.supabase.co";

  const rawKey =
    metaEnv["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    metaEnv["VITE_SUPABASE_ANON_KEY"] ||
    procEnv["SUPABASE_PUBLISHABLE_KEY"] ||
    procEnv["VITE_SUPABASE_PUBLISHABLE_KEY"];
  const SUPABASE_PUBLISHABLE_KEY =
    rawKey && rawKey !== "undefined" ? rawKey : "sb_publishable_WiczJQTx4afGJ02WAiUIUw_8YlWjkSP";

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

import type { SupabaseClient } from "@supabase/supabase-js";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type ClientWithAuth = Omit<SupabaseClient<Database>, "auth"> & { auth: any };

let _supabase: ClientWithAuth | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ClientWithAuth, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient() as unknown as ClientWithAuth;
    return Reflect.get(_supabase, prop, receiver);
  },
}) as ClientWithAuth;
